In [1]:
from __future__ import print_function, division
import requests
import re
import pandas as pd
from bs4 import BeautifulSoup
requests.__path__

['/anaconda3/lib/python3.7/site-packages/requests']

In [12]:
# URL for highest peaks and mean elevation
url = 'https://en.wikipedia.org/wiki/List_of_U.S._states_and_territories_by_elevation'
response = requests.get(url)

In [13]:
response.status_code # status code = 200 => OK

200

In [14]:
# convert to a BeautifulSoup Object
page = response.text
soup = BeautifulSoup(page, "lxml")

In [48]:
# Grab table from wikipedia page and iterate through table rows to get the table as a list
elevation_table = soup.find('table',{'class':'wikitable sortable'})
table_rows = elevation_table.findAll('tr')
table_as_list = []
for tr in table_rows:
    td = tr.find_all('td')
    row = [tr.text for tr in td]
    table_as_list.append(row)

table_as_list = table_as_list[1:]

[['\xa0Alabama\n',
  'Cheaha Mountain[9]\n',
  '2,413\xa0ft736\xa0m\n',
  '38\n',
  'Gulf of Mexico\n',
  'sea level\n',
  '500\xa0ft150\xa0m\n',
  '2,413\xa0ft736\xa0m\n'],
 ['\xa0Alaska\n',
  'Denali[10]\n',
  '20,310\xa0ft6190.5\xa0m\n',
  '1\n',
  'Gulf of Alaska, Bering Sea, and Arctic Ocean\n',
  'sea level\n',
  '1,900\xa0ft580\xa0m\n',
  '20,310\xa0ft6190.5\xa0m\n'],
 ['\xa0American Samoa\n',
  'Lata Mountain on Ta‘ū island[11]\n',
  '3,163\xa0ft964\xa0m\n',
  '36\n',
  'Pacific Ocean\n',
  'sea level\n',
  'NA\n',
  '3,163\xa0ft964\xa0m\n'],
 ['\xa0Arizona\n',
  'Humphreys Peak[12]\n',
  '12,637\xa0ft3852\xa0m\n',
  '12\n',
  'Colorado River at Sonora border, San Luis, Arizona\n',
  '72\xa0ft22\xa0m\n',
  '4,100\xa0ft1250\xa0m\n',
  '12,565\xa0ft3830\xa0m\n'],
 ['\xa0Arkansas\n',
  'Mount Magazine[13]\n',
  '2,753\xa0ft839\xa0m\n',
  '37\n',
  'Ouachita River at Louisiana border\n',
  '55\xa0ft17\xa0m\n',
  '650\xa0ft200\xa0m\n',
  '2,698\xa0ft822\xa0m\n'],
 ['\xa0California\n',
  'Mount Whitney[14][15]\n',
  '14,505\xa0ft4421.0\xa0m\n',
  '2\n',
  'Badwater Basin in Death Valley[1][2][16]\n',
  '−279\xa0ft−85\xa0m\n',
  '2,900\xa0ft880\xa0m\n',
  '14,783\xa0ft4506\xa0m\n'],
 ['\xa0Colorado\n',
  'Mount Elbert[17][18]\n',
  '14,440\xa0ft4401.2\xa0m\n',
  '3\n',
  'Arikaree River at Kansas border[19][20]\n',
  '3,317\xa0ft1011\xa0m\n',
  '6,800\xa0ft2070\xa0m\n',
  '11,123\xa0ft3390\xa0m\n'],
 ['\xa0Connecticut\n',
  'Massachusetts border on south side of Mount Frissell[21]\n',
  '2,379\xa0ft725\xa0m\n',
  '39\n',
  'Long Island Sound\n',
  'sea level\n',
  '500\xa0ft150\xa0m\n',
  '2,379\xa0ft725\xa0m\n'],
 ['\xa0Delaware\n',
  'Near the Ebright Azimuth[22][23]\n',
  '447\xa0ft136\xa0m\n',
  '54\n',
  'Atlantic Ocean\n',
  'sea level\n',
  '60\xa0ft20\xa0m\n',
  '447\xa0ft136\xa0m\n'],
 ['\xa0District of Columbia\n',
  'Fort Reno[24]\n',
  '409\xa0ft125\xa0m\n',
  '55\n',
  'Potomac River at eastern Maryland border\n',
  '1.0\xa0ft0.3\xa0m\n',
  '150\xa0ft50\xa0m\n',
  '408\xa0ft124\xa0m\n'],
 ['\xa0Florida\n',
  'Britton Hill\n',
  '345\xa0ft105\xa0m\n',
  '56\n',
  'Atlantic Ocean and Gulf of Mexico\n',
  'sea level\n',
  '100\xa0ft30\xa0m\n',
  '345\xa0ft105\xa0m\n'],
 [' Georgia\n',
  'Brasstown Bald\n',
  '4,784\xa0ft1458\xa0m\n',
  '25\n',
  'Atlantic Ocean\n',
  'sea level\n',
  '600\xa0ft180\xa0m\n',
  '4,784\xa0ft1458\xa0m\n'],
 ['\xa0Guam\n',
  'Mount Lamlam\n',
  '1,332\xa0ft406\xa0m[25]\n',
  '48\n',
  'Pacific Ocean\n',
  'sea level\n',
  'NA\n',
  '1,332\xa0ft406\xa0m\n'],
 ['\xa0Hawaii\n',
  "Mauna Kea[26][27] on the Island of Hawai'i\n",
  '13,803\xa0ft4207\xa0m\n',
  '6\n',
  'Pacific Ocean\n',
  'sea level\n',
  '3,030\xa0ft920\xa0m\n',
  '13,803\xa0ft4207\xa0m\n'],
 ['\xa0Idaho\n',
  'Borah Peak[28]\n',
  '12,668\xa0ft3861\xa0m\n',
  '11\n',
  'Confluence of Snake River and Clearwater River\n',
  '713\xa0ft217\xa0m\n',
  '5,000\xa0ft1520\xa0m\n',
  '11,954\xa0ft3644\xa0m\n'],
 ['\xa0Illinois\n',
  'Charles Mound[29]\n',
  '1,235\xa0ft376\xa0m\n',
  '50\n',
  'Confluence of Mississippi River and Ohio River\n',
  '280\xa0ft85\xa0m\n',
  '600\xa0ft180\xa0m\n',
  '955\xa0ft291\xa0m\n'],
 ['\xa0Indiana\n',
  'Hoosier Hill\n',
  '1,257\xa0ft383\xa0m\n',
  '49\n',
  'Confluence of Wabash River and Ohio River\n',
  '320\xa0ft97\xa0m\n',
  '700\xa0ft210\xa0m\n',
  '937\xa0ft286\xa0m\n'],
 ['\xa0Iowa\n',
  'Hawkeye Point\n',
  '1,671\xa0ft509\xa0m\n',
  '45\n',
  'Confluence of Mississippi River and Des Moines River\n',
  '480\xa0ft146\xa0m\n',
  '1,100\xa0ft340\xa0m\n',
  '1,191\xa0ft363\xa0m\n'],
 ['\xa0Kansas\n',
  'Mount Sunflower\n',
  '4,041\xa0ft1232\xa0m\n',
  '29\n',
  'Verdigris River at Oklahoma border\n',
  '679\xa0ft207\xa0m\n',
  '2,000\xa0ft610\xa0m\n',
  '3,361\xa0ft1025\xa0m\n'],
 ['\xa0Kentucky\n',
  'Black Mountain\n',
  '4,145\xa0ft1263\xa0m\n',
  '28\n',
  'Mississippi River at Kentucky Bend\n',
  '257\xa0ft78\xa0m\n',
  '750\xa0ft230\xa0m\n',
  '3,887\xa0ft1185\xa0m\n'],
 ['\xa0Louisiana\n',
  'Driskill Mountain\n',
  '535\xa0ft163\xa0m\n',
  '53\n',
  'New Orleans\n',
  '−8\xa0ft−2.4\xa0m\n',
  '100\xa0ft30\xa0m\n',
  '543\xa0ft165\xa0m\n'],
 ['\xa0Maine\n',
  'Mount Katahdin[30]\n',
  '5,270\xa0ft1606.4\xa0m\n',
  '22\n',
  'Atlantic Ocean\n',
  'sea level\n',
  '600\xa0ft180\xa0m\n',
  '5,270\xa0ft1606.4\xa0m\n'],
 ['\xa0Maryland\n',
  'Hoye-Crest\n',
  '3,360\xa0ft1024\xa0m\n',
  '33\n',
  'Atlantic Ocean\n',
  'sea level\n',
  '350\xa0ft110\xa0m\n',
  '3,360\xa0ft1024\xa0m\n'],
 ['\xa0Massachusetts\n',
  'Mount Greylock[31]\n',
  '3,489\xa0ft1063\xa0m\n',
  '32\n',
  'Atlantic Ocean\n',
  'sea level\n',
  '500\xa0ft150\xa0m\n',
  '3,489\xa0ft1063\xa0m\n'],
 ['\xa0Michigan\n',
  'Mount Arvon\n',
  '1,979\xa0ft603\xa0m\n',
  '41\n',
  'Lake Erie\n',
  '571\xa0ft174\xa0m\n',
  '900\xa0ft270\xa0m\n',
  '1,408\xa0ft429\xa0m\n'],
 ['\xa0Minnesota\n',
  'Eagle Mountain\n',
  '2,302\xa0ft701\xa0m\n',
  '40\n',
  'Lake Superior\n',
  '601\xa0ft183\xa0m\n',
  '1,200\xa0ft370\xa0m\n',
  '1,700\xa0ft518\xa0m\n'],
 ['\xa0Mississippi\n',
  'Woodall Mountain[32]\n',
  '807\xa0ft246\xa0m\n',
  '52\n',
  'Gulf of Mexico\n',
  'sea level\n',
  '300\xa0ft90\xa0m\n',
  '807\xa0ft246\xa0m\n'],
 ['\xa0Missouri\n',
  'Taum Sauk Mountain\n',
  '1,772\xa0ft540\xa0m\n',
  '44\n',
  'Saint Francis River at southern Arkansas border\n',
  '230\xa0ft70\xa0m\n',
  '800\xa0ft240\xa0m\n',
  '1,542\xa0ft470\xa0m\n'],
 ['\xa0Montana\n',
  'Granite Peak[33]\n',
  '12,807\xa0ft3903.5\xa0m\n',
  '10\n',
  'Kootenai River at Idaho border\n',
  '1,804\xa0ft550\xa0m\n',
  '3,400\xa0ft1040\xa0m\n',
  '11,003\xa0ft3354\xa0m\n'],
 ['\xa0Nebraska\n',
  'Panorama Point\n',
  '5,427\xa0ft1654\xa0m\n',
  '20\n',
  'Missouri River at Kansas border\n',
  '840\xa0ft256\xa0m\n',
  '2,600\xa0ft790\xa0m\n',
  '4,587\xa0ft1398\xa0m\n'],
 ['\xa0Nevada\n',
  'Boundary Peak[34]\n',
  '13,147\xa0ft4007\xa0m\n',
  '9\n',
  'Colorado River at California border\n',
  '481\xa0ft147\xa0m\n',
  '5,500\xa0ft1680\xa0m\n',
  '12,665\xa0ft3860\xa0m\n'],
 ['\xa0New Hampshire\n',
  'Mount Washington[35][36]\n',
  '6,288\xa0ft1917\xa0m\n',
  '18\n',
  'Atlantic Ocean\n',
  'sea level\n',
  '1,000\xa0ft300\xa0m\n',
  '6,288\xa0ft1917\xa0m\n'],
 ['\xa0New Jersey\n',
  'High Point\n',
  '1,803\xa0ft550\xa0m\n',
  '43\n',
  'Atlantic Ocean\n',
  'sea level\n',
  '250\xa0ft80\xa0m\n',
  '1,803\xa0ft550\xa0m\n'],
 ['\xa0New Mexico\n',
  'Wheeler Peak[37]\n',
  '13,167\xa0ft4013.3\xa0m\n',
  '8\n',
  'Red Bluff Reservoir on Texas border\n',
  '2,844\xa0ft867\xa0m\n',
  '5,700\xa0ft1740\xa0m\n',
  '10,323\xa0ft3147\xa0m\n'],
 ['\xa0New York\n',
  'Mount Marcy[38]\n',
  '5,343\xa0ft1628.57\xa0m\n',
  '21\n',
  'Atlantic Ocean\n',
  'sea level\n',
  '1,000\xa0ft300\xa0m\n',
  '5,343\xa0ft1628.57\xa0m\n'],
 ['\xa0North Carolina\n',
  'Mount Mitchell[39]\n',
  '6,684\xa0ft2037\xa0m\n',
  '16\n',
  'Atlantic Ocean\n',
  'sea level\n',
  '700\xa0ft210\xa0m\n',
  '6,684\xa0ft2037\xa0m\n'],
 ['\xa0\xa0North Dakota\n',
  'White Butte\n',
  '3,508\xa0ft1069\xa0m\n',
  '31\n',
  'Red River of the North at Manitoba border\n',
  '751\xa0ft229\xa0m\n',
  '1,900\xa0ft580\xa0m\n',
  '2,757\xa0ft840\xa0m\n'],
 ['\xa0Northern Mariana Islands\n',
  'Unnamed point on Agrihan island\n',
  '3,166\xa0ft965\xa0m[40]\n',
  '35\n',
  'Pacific Ocean\n',
  'sea level\n',
  'NA\n',
  '3,166\xa0ft965\xa0m\n'],
 ['\xa0Ohio\n',
  'Campbell Hill\n',
  '1,549\xa0ft472\xa0m\n',
  '47\n',
  'Ohio River at Indiana border\n',
  '455\xa0ft139\xa0m\n',
  '850\xa0ft260\xa0m\n',
  '1,094\xa0ft333\xa0m\n'],
 ['\xa0Oklahoma\n',
  'Black Mesa\n',
  '4,975\xa0ft1516\xa0m\n',
  '23\n',
  'Little River at Arkansas border\n',
  '289\xa0ft88\xa0m\n',
  '1,300\xa0ft400\xa0m\n',
  '4,686\xa0ft1428\xa0m\n'],
 ['\xa0Oregon\n',
  'Mount Hood[41]\n',
  '11,249\xa0ft3428.8\xa0m\n',
  '13\n',
  'Pacific Ocean\n',
  'sea level\n',
  '3,300\xa0ft1010\xa0m\n',
  '11,249\xa0ft3428.8\xa0m\n'],
 ['\xa0Pennsylvania\n',
  'Mount Davis\n',
  '3,213\xa0ft979\xa0m\n',
  '34\n',
  'Delaware River at Delaware border\n',
  'sea level\n',
  '1,100\xa0ft340\xa0m\n',
  '3,213\xa0ft979\xa0m\n'],
 ['\xa0Puerto Rico\n',
  'Cerro de Punta\n',
  '4,390\xa0ft1338\xa0m[42]\n',
  '27\n',
  'Atlantic Ocean (Caribbean sea)\n',
  'sea level\n',
  '856\xa0ft261\xa0m\n',
  '4,390\xa0ft1338\xa0m\n'],
 ['\xa0Rhode Island\n',
  'Jerimoth Hill\n',
  '811\xa0ft247\xa0m\n',
  '51\n',
  'Atlantic Ocean\n',
  'sea level\n',
  '200\xa0ft60\xa0m\n',
  '811\xa0ft247\xa0m\n'],
 ['\xa0South Carolina\n',
  'Sassafras Mountain\n',
  '3,560\xa0ft1085\xa0m\n',
  '30\n',
  'Atlantic Ocean\n',
  'sea level\n',
  '350\xa0ft110\xa0m\n',
  '3,560\xa0ft1085\xa0m\n'],
 ['\xa0South Dakota\n',
  'Black Elk Peak[43]\n',
  '7,244\xa0ft2208\xa0m\n',
  '15\n',
  'Big Stone Lake on Minnesota border\n',
  '968\xa0ft295\xa0m\n',
  '2,200\xa0ft670\xa0m\n',
  '6,276\xa0ft1913\xa0m\n'],
 ['\xa0Tennessee\n',
  'Clingmans Dome\n',
  '6,643\xa0ft2025\xa0m\n',
  '17\n',
  'Mississippi River at Mississippi border\n',
  '178\xa0ft54\xa0m\n',
  '900\xa0ft270\xa0m\n',
  '6,466\xa0ft1971\xa0m\n'],
 ['\xa0Texas\n',
  'Guadalupe Peak[44]\n',
  '8,751\xa0ft2667\xa0m\n',
  '14\n',
  'Gulf of Mexico\n',
  'sea level\n',
  '1,700\xa0ft520\xa0m\n',
  '8,751\xa0ft2667\xa0m\n'],
 [' United States Minor Outlying Islands\n',
  'Unnamed point on Navassa Island\n',
  '279\xa0ft85\xa0m[45]\n',
  '57\n',
  'Pacific Ocean (8 islands) and Caribbean Sea (Navassa Island)\n',
  'sea level\n',
  'NA\n',
  '279\xa0ft85\xa0m\n'],
 ['\xa0Utah\n',
  'Kings Peak[46]\n',
  '13,534\xa0ft4125\xa0m\n',
  '7\n',
  'Beaver Dam Wash at Arizona border\n',
  '2,180\xa0ft664\xa0m\n',
  '6,100\xa0ft1860\xa0m\n',
  '11,354\xa0ft3461\xa0m\n'],
 ['\xa0Vermont\n',
  'Mount Mansfield[47]\n',
  '4,395\xa0ft1340\xa0m\n',
  '26\n',
  'Lake Champlain\n',
  '95\xa0ft29\xa0m\n',
  '1,000\xa0ft300\xa0m\n',
  '4,300\xa0ft1311\xa0m\n'],
 [' Virgin Islands (U.S.)\n',
  'Crown Mountain on the island of Saint Thomas\n',
  '1,555\xa0ft474\xa0m[48]\n',
  '46\n',
  'Atlantic Ocean (Caribbean Sea)\n',
  'sea level\n',
  'NA\n',
  '1,555\xa0ft474\xa0m\n'],
 ['\xa0Virginia\n',
  'Mount Rogers\n',
  '5,729\xa0ft1746\xa0m\n',
  '19\n',
  'Atlantic Ocean\n',
  'sea level\n',
  '950\xa0ft290\xa0m\n',
  '5,729\xa0ft1746\xa0m\n'],
 [' Washington\n',
  'Mount Rainier[49]\n',
  '14,417\xa0ft4394\xa0m\n',
  '4\n',
  'Pacific Ocean\n',
  'sea level\n',
  '1,700\xa0ft520\xa0m\n',
  '14,417\xa0ft4394\xa0m\n'],
 ['\xa0West Virginia\n',
  'Spruce Knob[50]\n',
  '4,863\xa0ft1482.1\xa0m\n',
  '24\n',
  'Potomac River at Virginia border\n',
  '240\xa0ft73\xa0m\n',
  '1,500\xa0ft460\xa0m\n',
  '4,623\xa0ft1409\xa0m\n'],
 ['\xa0Wisconsin\n',
  'Timms Hill\n',
  '1,951\xa0ft595\xa0m\n',
  '42\n',
  'Lake Michigan\n',
  '579\xa0ft176\xa0m\n',
  '1,050\xa0ft320\xa0m\n',
  '1,372\xa0ft418\xa0m\n'],
 ['\xa0Wyoming\n',
  'Gannett Peak[51]\n',
  '13,809\xa0ft4209.1\xa0m\n',
  '5\n',
  'Belle Fourche River at South Dakota border\n',
  '3,101\xa0ft945\xa0m\n',
  '6,700\xa0ft2040\xa0m\n',
  '10,709\xa0ft3264\xa0m\n'],
 ['United States\n',
  'Denali,[10] Alaska\n',
  '20,310\xa0ft6190.5\xa0m\n',
  '\n',
  'Badwater Basin,[16] California\n',
  '−279\xa0ft−85\xa0m\n',
  '2,500\xa0ft760\xa0m\n',
  '20,589\xa0ft6275.5\xa0m\n']]

In [74]:
# Iterate through the table (as a list) to get state, highest peak, and mean elevation

states_list = []
highest_list = []
mean_list = []
for info in table_as_list:
    # extract state
    state = str(info[0]).strip()
    states_list.append(state)
    
    # extract highest peak
    highest = str(info[2]).strip()
    highest_list.append(float(highest.split('ft')[0].strip().replace(',', '')))
    
    # extract mean elevation
    mean = str(info[6]).strip()
    try:
        mean_list.append(float(mean.split('ft')[0].strip().replace(',', '')))
    except ValueError:
        mean_list.append(0)
    
# print(states_list)
# print(highest_list)
# print(mean_list)

['Alabama', 'Alaska', 'American Samoa', 'Arizona', 'Arkansas', 'California', 'Colorado', 'Connecticut', 'Delaware', 'District of Columbia', 'Florida', 'Georgia', 'Guam', 'Hawaii', 'Idaho', 'Illinois', 'Indiana', 'Iowa', 'Kansas', 'Kentucky', 'Louisiana', 'Maine', 'Maryland', 'Massachusetts', 'Michigan', 'Minnesota', 'Mississippi', 'Missouri', 'Montana', 'Nebraska', 'Nevada', 'New Hampshire', 'New Jersey', 'New Mexico', 'New York', 'North Carolina', 'North Dakota', 'Northern Mariana Islands', 'Ohio', 'Oklahoma', 'Oregon', 'Pennsylvania', 'Puerto Rico', 'Rhode Island', 'South Carolina', 'South Dakota', 'Tennessee', 'Texas', 'United States Minor Outlying Islands', 'Utah', 'Vermont', 'Virgin Islands (U.S.)', 'Virginia', 'Washington', 'West Virginia', 'Wisconsin', 'Wyoming', 'United States']
[2413.0, 20310.0, 3163.0, 12637.0, 2753.0, 14505.0, 14440.0, 2379.0, 447.0, 409.0, 345.0, 4784.0, 1332.0, 13803.0, 12668.0, 1235.0, 1257.0, 1671.0, 4041.0, 4145.0, 535.0, 5270.0, 3360.0, 3489.0, 1979.0, 2302.0, 807.0, 1772.0, 12807.0, 5427.0, 13147.0, 6288.0, 1803.0, 13167.0, 5343.0, 6684.0, 3508.0, 3166.0, 1549.0, 4975.0, 11249.0, 3213.0, 4390.0, 811.0, 3560.0, 7244.0, 6643.0, 8751.0, 279.0, 13534.0, 4395.0, 1555.0, 5729.0, 14417.0, 4863.0, 1951.0, 13809.0, 20310.0]
[500.0, 1900.0, 0, 4100.0, 650.0, 2900.0, 6800.0, 500.0, 60.0, 150.0, 100.0, 600.0, 0, 3030.0, 5000.0, 600.0, 700.0, 1100.0, 2000.0, 750.0, 100.0, 600.0, 350.0, 500.0, 900.0, 1200.0, 300.0, 800.0, 3400.0, 2600.0, 5500.0, 1000.0, 250.0, 5700.0, 1000.0, 700.0, 1900.0, 0, 850.0, 1300.0, 3300.0, 1100.0, 856.0, 200.0, 350.0, 2200.0, 900.0, 1700.0, 0, 6100.0, 1000.0, 0, 950.0, 1700.0, 1500.0, 1050.0, 6700.0, 2500.0]

In [82]:
elevation_df = pd.DataFrame(
    {'State': states_list,
     'Highest Point': highest_list,
     'Mean Elevation': mean_list
    })
elevation_df.set_index('State', inplace = True)

In [84]:
elevation_df.sample(10)

                          Highest Point  Mean Elevation
State
Northern Mariana Islands         3166.0             0.0
Vermont                          4395.0          1000.0
New Hampshire                    6288.0          1000.0
Montana                         12807.0          3400.0
Texas                            8751.0          1700.0
United States                   20310.0          2500.0
Michigan                         1979.0           900.0
South Dakota                     7244.0          2200.0
Washington                      14417.0          1700.0
Georgia                          4784.0           600.0