In [1]:
from __future__ import print_function, division
import requests
import re
import pandas as pd
from bs4 import BeautifulSoup
requests.__path__

['/anaconda3/lib/python3.7/site-packages/requests']

In [4]:
# URL for average annual state precipitation

url = 'https://www.currentresults.com/Weather/US/average-annual-state-precipitation.php'
response = requests.get(url)

In [5]:
response.status_code # status code = 200 => OK

200

In [6]:
# convert to a BeautifulSoup Object

page = response.text
soup = BeautifulSoup(page, "lxml")

In [7]:
# Iterate through 'td' tags on table and extract state name and rainfall (in inches) with a counter,
# putting them into a dict

rainfall = {}
count = 0
for link in soup.find_all('td'):
    trimmed_text = str(link.renderContents().strip())
    if count % 4 == 0:
        state = re.search(">(.*)<", trimmed_text).group(1)
    if (count-1) % 4 == 0:
        rainfall[state] = float(trimmed_text[2:-1])

    count += 1

print(rainfall)

{'Alabama': 58.3, 'Alaska': 22.5, 'Arizona': 13.6, 'Arkansas': 50.6, 'California': 22.2, 'Colorado': 15.9, 'Connecticut': 50.3, 'Delaware': 45.7, 'Florida': 54.5, 'Georgia': 50.7, 'Hawaii': 63.7, 'Idaho': 18.9, 'Illinois': 39.2, 'Indiana': 41.7, 'Iowa': 34.0, 'Kansas': 28.9, 'Kentucky': 48.9, 'Louisiana': 60.1, 'Maine': 42.2, 'Maryland': 44.5, 'Massachusetts': 47.7, 'Michigan': 32.8, 'Minnesota': 27.3, 'Mississippi': 59.0, 'Missouri': 42.2, 'Montana': 15.3, 'Nebraska': 23.6, 'Nevada': 9.5, 'New Hampshire': 43.4, 'New Jersey': 47.1, 'New Mexico': 14.6, 'New York': 41.8, 'North Carolina': 50.3, 'North Dakota': 17.8, 'Ohio': 39.1, 'Oklahoma': 36.5, 'Oregon': 27.4, 'Pennsylvania': 42.9, 'Rhode Island': 47.9, 'South Carolina': 49.8, 'South Dakota': 20.1, 'Tennessee': 54.2, 'Texas': 28.9, 'Utah': 12.2, 'Vermont': 42.7, 'Virginia': 44.3, 'Washington': 38.4, 'West Virginia': 45.2, 'Wisconsin': 32.6, 'Wyoming': 12.9}

In [9]:
# Send dict to a df

rainfall_df = pd.DataFrame.from_dict(rainfall, orient='index', columns=['Rainfall (Inches)'])
rainfall_df.head(50)

                Rainfall (Inches)
Alabama                      58.3
Alaska                       22.5
Arizona                      13.6
Arkansas                     50.6
California                   22.2
Colorado                     15.9
Connecticut                  50.3
Delaware                     45.7
Florida                      54.5
Georgia                      50.7
Hawaii                       63.7
Idaho                        18.9
Illinois                     39.2
Indiana                      41.7
Iowa                         34.0
Kansas                       28.9
Kentucky                     48.9
Louisiana                    60.1
Maine                        42.2
Maryland                     44.5
Massachusetts                47.7
Michigan                     32.8
Minnesota                    27.3
Mississippi                  59.0
Missouri                     42.2
Montana                      15.3
Nebraska                     23.6
Nevada                        9.5
New Hampshire                43.4
New Jersey                   47.1
New Mexico                   14.6
New York                     41.8
North Carolina               50.3
North Dakota                 17.8
Ohio                         39.1
Oklahoma                     36.5
Oregon                       27.4
Pennsylvania                 42.9
Rhode Island                 47.9
South Carolina               49.8
South Dakota                 20.1
Tennessee                    54.2
Texas                        28.9
Utah                         12.2
Vermont                      42.7
Virginia                     44.3
Washington                   38.4
West Virginia                45.2
Wisconsin                    32.6
Wyoming                      12.9