In [2]:
# Import libraries for scraping

from __future__ import print_function, division
import requests
import re
import pandas as pd
from bs4 import BeautifulSoup
requests.__path__

['/anaconda3/lib/python3.7/site-packages/requests']

In [3]:
# URLs for happiness by states from studies done in 2016, 2017, and 2018

url2018 = 'https://wallethub.com/edu/happiest-states/6959/#methodology'
url2017 = 'https://www.livescience.com/61744-happiest-states-2017-full-list.html'
url2016 = 'https://www.livescience.com/57716-happiest-states-2016-full-list.html'

response2018 = requests.get(url2018)
response2017 = requests.get(url2017)
response2016 = requests.get(url2016)

In [35]:
# Check the status! 
response2018.status_code # status code = 200 => OK

200

In [36]:
# Etc.
response2017.status_code # status code = 200 => OK

200

In [4]:
# Etc. 
response2016.status_code # status code = 200 => OK

403

In [8]:
# Take care of 2018 first

# convert to a BeautifulSoup Object

page2018 = response2018.text
soup2018 = BeautifulSoup(page2018, "lxml")

In [9]:
# Iterate through 'td' tags on table and extract state name and happiness with a counter,
# putting them into a dict

happiness2018 = {}
count = 0
for link in soup2018.find_all('td'):
    trimmed_text = str(link.renderContents().strip())
#     print(count, trimmed_text)
    if (count + 5) % 6 == 0:
        state = trimmed_text[2:-1]
    if (count + 4) % 6 == 0:
        happiness2018[state] = float(trimmed_text[2:-1])

    count += 1

print(happiness2018)

{'Hawaii': 68.27, 'Utah': 67.84, 'Minnesota': 67.26, 'North Dakota': 65.62, 'California': 63.14, 'Idaho': 63.09, 'Maryland': 61.78, 'Iowa': 61.07, 'South Dakota': 60.8, 'Nebraska': 59.11, 'Wisconsin': 58.87, 'Connecticut': 58.24, 'New Jersey': 58.1, 'New York': 57.35, 'Virginia': 57.35, 'Massachusetts': 56.85, 'Washington': 56.44, 'Colorado': 55.38, 'Georgia': 55.15, 'North Carolina': 53.69, 'Arizona': 52.92, 'Texas': 52.56, 'Illinois': 52.47, 'New Hampshire': 52.37, 'Kansas': 52.3, 'Nevada': 51.8, 'Delaware': 51.67, 'Montana': 51.08, 'Florida': 51.01, 'Pennsylvania': 50.54, 'Rhode Island': 50.44, 'Indiana': 50.2, 'Maine': 49.81, 'Michigan': 49.52, 'Wyoming': 48.9, 'South Carolina': 48.26, 'Ohio': 48.19, 'Vermont': 48.18, 'Oregon': 48.05, 'Tennessee': 46.13, 'New Mexico': 43.35, 'Missouri': 42.76, 'Mississippi': 41.63, 'Kentucky': 39.42, 'Alabama': 39.35, 'Oklahoma': 38.89, 'Alaska': 38.21, 'Louisiana': 37.15, 'Arkansas': 36.61, 'West Virginia': 33.42}

In [10]:
# Send dict to a df

happiness2018_df = pd.DataFrame.from_dict(happiness2018, orient='index', columns=['Happiness (2018)'])
happiness2018_df.head(50)

                Happiness (2018)
Hawaii                     68.27
Utah                       67.84
Minnesota                  67.26
North Dakota               65.62
California                 63.14
Idaho                      63.09
Maryland                   61.78
Iowa                       61.07
South Dakota               60.80
Nebraska                   59.11
Wisconsin                  58.87
Connecticut                58.24
New Jersey                 58.10
New York                   57.35
Virginia                   57.35
Massachusetts              56.85
Washington                 56.44
Colorado                   55.38
Georgia                    55.15
North Carolina             53.69
Arizona                    52.92
Texas                      52.56
Illinois                   52.47
New Hampshire              52.37
Kansas                     52.30
Nevada                     51.80
Delaware                   51.67
Montana                    51.08
Florida                    51.01
Pennsylvania               50.54
Rhode Island               50.44
Indiana                    50.20
Maine                      49.81
Michigan                   49.52
Wyoming                    48.90
South Carolina             48.26
Ohio                       48.19
Vermont                    48.18
Oregon                     48.05
Tennessee                  46.13
New Mexico                 43.35
Missouri                   42.76
Mississippi                41.63
Kentucky                   39.42
Alabama                    39.35
Oklahoma                   38.89
Alaska                     38.21
Louisiana                  37.15
Arkansas                   36.61
West Virginia              33.42

In [11]:
# Pickle
happiness2018_df.to_pickle('~/ds/metis/metisgh/project_luther/data/happy2018.pkl')

In [15]:
# 2017 next

# Scrape
page2017 = response2017.text
soup2017 = BeautifulSoup(page2017, "lxml")

In [16]:
# Iterate through 'li' tags on table and extract state name and happiness with a counter,
# putting them into a dict

happiness2017 = {}
count = 0
for link in soup2017.find_all('li'):
    trimmed_text = str(link.renderContents().strip())
    if count >= 33 and count <= 82:
        info = trimmed_text[2:-1].split()
        if len(info) > 2:
            state = info[0] + ' ' + info[1]
        else:
            state = info[0]
        happiness2017[state] = float(info[-1])

    count += 1

print(happiness2017)

{'South Dakota': 64.1, 'Vermont': 64.1, 'Hawaii': 63.4, 'Minnesota': 63.1, 'North Dakota': 63.1, 'Colorado': 62.9, 'New Hampshire': 62.8, 'Idaho': 62.8, 'Utah': 62.8, 'Montana': 62.8, 'Massachusetts': 62.5, 'Florida': 62.4, 'Texas': 62.3, 'California': 62.3, 'Arizona': 62.2, 'Wyoming': 62.1, 'Nebraska': 62.1, 'Virginia': 61.9, 'North Carolina': 61.8, 'Connecticut': 61.7, 'Iowa': 61.7, 'Washington': 61.7, 'New York': 61.7, 'Maine': 61.6, 'Alaska': 61.6, 'New Mexico': 61.6, 'Wisconsin': 61.6, 'New Jersey': 61.5, 'Tennessee': 61.5, 'Maryland': 61.3, 'Georgia': 61.3, 'Michigan': 61.3, 'Kansas': 61.2, 'Pennsylvania': 61.2, 'Oregon': 61.1, 'Illinois': 61.1, 'South Carolina': 61.0, 'Alabama': 60.8, 'Missouri': 60.7, 'Delaware': 60.7, 'Rhode Island': 60.5, 'Indiana': 60.4, 'Nevada': 60.2, 'Ohio': 60.0, 'Kentucky': 59.8, 'Oklahoma': 59.7, 'Mississippi': 59.6, 'Arkansas': 59.4, 'Louisiana': 58.9, 'West Virginia': 58.8}

In [17]:
# Send dict to a df
happiness2017_df = pd.DataFrame.from_dict(happiness2017, orient='index', columns=['Happiness (2017)'])
happiness2017_df.head(50)

                Happiness (2017)
South Dakota                64.1
Vermont                     64.1
Hawaii                      63.4
Minnesota                   63.1
North Dakota                63.1
Colorado                    62.9
New Hampshire               62.8
Idaho                       62.8
Utah                        62.8
Montana                     62.8
Massachusetts               62.5
Florida                     62.4
Texas                       62.3
California                  62.3
Arizona                     62.2
Wyoming                     62.1
Nebraska                    62.1
Virginia                    61.9
North Carolina              61.8
Connecticut                 61.7
Iowa                        61.7
Washington                  61.7
New York                    61.7
Maine                       61.6
Alaska                      61.6
New Mexico                  61.6
Wisconsin                   61.6
New Jersey                  61.5
Tennessee                   61.5
Maryland                    61.3
Georgia                     61.3
Michigan                    61.3
Kansas                      61.2
Pennsylvania                61.2
Oregon                      61.1
Illinois                    61.1
South Carolina              61.0
Alabama                     60.8
Missouri                    60.7
Delaware                    60.7
Rhode Island                60.5
Indiana                     60.4
Nevada                      60.2
Ohio                        60.0
Kentucky                    59.8
Oklahoma                    59.7
Mississippi                 59.6
Arkansas                    59.4
Louisiana                   58.9
West Virginia               58.8

In [18]:
# Pickle
happiness2017_df.to_pickle('~/ds/metis/metisgh/project_luther/data/happy2017.pkl')

In [46]:
# 2016 finally

# Scrape
page2016 = response2016.text
soup2016 = BeautifulSoup(page2016, "lxml")

In [47]:
# Iterate through 'p' tags on table and extract state name and happiness with a counter,
# putting them into a dict

happiness2016 = {}
count = 0
for link in soup2016.find_all('p'):
    trimmed_text = str(link.renderContents().strip())
    if count >= 2 and count <= 51:
        info = trimmed_text[2:-1].split()
        if len(info) > 3:
            state = info[1] + ' ' + info[2]
        else:
            state = info[1]
        try:
            happiness2016[state] = float(info[-1])
        except ValueError:
            happiness2016[state] = float(info[-1][:-8])

    count += 1

In [48]:
# Send dict to a df
happiness2016_df = pd.DataFrame.from_dict(happiness2016, orient='index', columns=['Happiness (2016)'])
happiness2016_df.head(50)

                Happiness (2016)
Hawaii                      65.2
Alaska                      64.0
South Dakota                63.7
Maine                       63.6
Colorado                    63.5
Vermont                     63.5
Arizona                     63.4
Montana                     63.2
Minnesota                   63.2
Texas                       63.1
Florida                     63.1
Wyoming                     63.0
California                  63.0
Massachusetts               63.0
Nebraska                    62.9
North Dakota                62.8
Utah                        62.8
Idaho                       62.7
Iowa                        62.6
New Mexico                  62.6
Virginia                    62.6
New Hampshire               62.6
Washington                  62.5
Oregon                      62.5
New Jersey                  62.5
North Carolina              62.4
South Carolina              62.3
Wisconsin                   62.3
Georgia                     62.3
Pennsylvania                62.1
Maryland                    62.0
Kansas                      61.8
New York                    61.8
Nevada                      61.8
Connecticut                 61.7
Missouri                    61.7
Illinois                    61.6
Tennessee                   61.5
Michigan                    61.4
Delaware                    61.4
Mississippi                 61.3
Rhode Island                61.3
Louisiana                   61.0
Alabama                     61.0
Ohio                        60.9
Arkansas                    60.8
Indiana                     60.5
Oklahoma                    60.5
Kentucky                    60.5
West Virginia               58.9

In [49]:
# Pickle
happiness2016_df.to_pickle('~/ds/metis/metisgh/project_luther/data/happy2016.pkl')